defaults: &defaults
  media_host: buddy-video-assets.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
  admins:
    - szinin@gmail.com
    - s.popov.design@gmail.com
  transloadit:
    uploads_bucket: 'buddy-assets'
    media_bucket: 'buddy-video-assets'
  mobile_site_url: 'https://m.connectpal.com'

jwplayer: &jwplayer
  jwplayer:
    script_path: //jwpsrv.com/library/i2XZ_MYyEeOEtyIACrqE1A.js

development:
  <<: *defaults
  http_access: false
  javascript:
    log_level: 3
    <<: *jwplayer

production:
  <<: *defaults
  media_host: connectpal-media.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
    <<: *jwplayer
  transloadit:
    uploads_bucket: 'connectpal-uploads'
    media_bucket: 'connectpal-media'

staging:
  <<: *defaults
  http_access:
    name: buddy
    password: staging
  javascript:
    log_level: 3
    <<: *jwplayer

test:
  <<: *defaults
  http_access: false
