defaults: &defaults
  stripe_percent: 0.02
  media_host: buddy-video-assets.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
  admins:
    - szinin@gmail.com
    - s.popov.design@gmail.com
  transloadit:
    uploads_bucket: 'buddy-assets'
    media_bucket: 'buddy-video-assets'
  mobile_site_url: 'https://m.connectpal.com'
  mobile_redirects:
    "/account_info/settings": "/settings/account/personal"
    "/account_info/billing_information": "/settings/account/billing"
    "/account_info/dialogues": "/dialogues"
    "/account_info/details": "/details"
    "/account_info/edit_payment_information": "/settings/profile/payout"

jwplayer: &jwplayer
  jwplayer:
    script_path: //jwpsrv.com/library/i2XZ_MYyEeOEtyIACrqE1A.js

development:
  <<: *defaults
  http_access: false
  javascript:
    log_level: 3
    <<: *jwplayer

production:
  <<: *defaults
  media_host: connectpal-media.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
    <<: *jwplayer
  transloadit:
    uploads_bucket: 'connectpal-uploads'
    media_bucket: 'connectpal-media'
  assets_bucket: connectpal-assets

staging:
  <<: *defaults
  http_access:
    name: buddy
    password: staging
  javascript:
    log_level: 3
    <<: *jwplayer
  mobile_site_url: 'https://ms.connectpal.com'
  assets_bucket: buddy-assets

test:
  <<: *defaults
  http_access: false
