defaults: &defaults
  media_host: buddy-video-assets.s3.amazonaws.com
  http_access:
    name: buddy
    password: staging
  javascript:
    log_level: 0
  admins:
    - szinin@gmail.com
    - s.popov.design@gmail.com

jwplayer: &jwplayer
  jwplayer:
    script_path: //jwpsrv.com/library/i2XZ_MYyEeOEtyIACrqE1A.js

development:
  <<: *defaults
  http_access: false
  javascript:
    log_level: 3
    <<: *jwplayer

production:
  <<: *defaults
  media_host: connectpal-media.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
    <<: *jwplayer

staging:
  <<: *defaults
  javascript:
    log_level: 3
    <<: *jwplayer

test:
  <<: *defaults
  http_access: false
