defaults: &defaults
  api_version: 0.0.2
  stripe_pk: pk_test_uYMjbYk64dDXYZhlHS4mk8UC
  stripe_percent: 0.018
  enable_cc_locks: yes
  enable_post_clean_job: no
  media_host: buddy-video-assets.s3.amazonaws.com
  http_access: false
  javascript:
    log_level: 0
  admins:
    - szinin@gmail.com
    - s.popov.design@gmail.com
    - redworker@gmail.com
  emails:
    debug: debug@connectpal.com
    reports: reports@connectpal.com
    operations: operations@connectpal.com
    business: business@connectpal.com
    deleted_posts:
      - will@connectpal.com
      - andy@connectpal.com
  transloadit:
    uploads_bucket: 'buddy-assets'
    media_bucket: 'buddy-video-assets'
  mobile_site_url: 'https://m.connectpal.com'
  mobile_redirects:
    "/account_info/settings": "/settings/account/personal"
    "/account_info/billing_information": "/settings/account/billing"
    "/account_info/dialogues": "/dialogues"
    "/account_info/details": "/details"
    "/account_info/edit_payment_information": "/settings/profile/payout"
  adult_words:
    - 187
    - 3x
    - 69
    - action
    - anaconda
    - anya
    - ass
    - azz
    - babe
    - baby
    - bad
    - barb
    - barbie
    - bare
    - bbw
    - bet
    - bitch
    - body
    - boobs
    - boooty
    - boot
    - bootie
    - booty
    - bum
    - bun
    - bunz
    - busty
    - butt
    - cheek
    - chunky
    - clit
    - cock
    - cum
    - cup
    - curvy
    - cyber
    - deep
    - deesire
    - desire
    - dick
    - dirty
    - doll
    - drugs
    - ebony
    - erotic
    - erotica
    - exotic
    - fantasy
    - fat
    - fetish
    - freak
    - gape
    - hard
    - haze
    - hoe
    - honey
    - hung
    - jug
    - juggs
    - juice
    - juicy
    - key
    - kiss
    - kitty
    - lust
    - milk
    - mistress
    - model
    - mowett
    - nasty
    - naughty
    - nympho
    - penis
    - phat
    - playboy
    - porn
    - pretty
    - pussy
    - rape
    - rose
    - rossi
    - savage
    - secret
    - sex
    - sexi
    - sin
    - slut
    - suck
    - sucks
    - suicide
    - sultry
    - thick
    - thick
    - thot
    - throat
    - tit
    - tits
    - titty
    - tongue
    - tranny
    - uncut
    - virgin
    - volup
    - voluptuous
    - wet
    - wett
    - whore
    - wood
    - xx
    - xxl
    - xxx
    - zzz

  forbidden_email_domains:
    - yopmail.com
    - yopmail.fr
    - yopmail.net
    - cool.fr.nf
    - jetable.fr.nf
    - nospam.ze.tc
    - nomail.xl.cx
    - mega.zik.dj
    - speed.1s.fr
    - courriel.fr.nf
    - moncourrier.fr.nf
    - monemail.fr.nf
    - monmail.fr.nf

jwplayer: &jwplayer
  jwplayer:
    script_path: //jwpsrv.com/library/i2XZ_MYyEeOEtyIACrqE1A.js

development:
  <<: *defaults
  enable_cc_locks: no
  http_access: false
  javascript:
    log_level: 3
    <<: *jwplayer

production:
  <<: *defaults
  enable_post_clean_job: yes
  media_host: connectpal-media.s3.amazonaws.com
  stripe_pk: pk_live_rVrv3urJfHHncX0oOQmgKceL
  http_access: false
  javascript:
    log_level: 0
    <<: *jwplayer
  transloadit:
    uploads_bucket: 'connectpal-uploads'
    media_bucket: 'connectpal-media'
  assets_bucket: connectpal-assets

staging:
  <<: *defaults
  enable_cc_locks: no
  http_access:
    name: buddy
    password: staging
  javascript:
    log_level: 3
    <<: *jwplayer
  mobile_site_url: 'https://ms.connectpal.com'
  assets_bucket: buddy-assets

test:
  <<: *defaults
  enable_post_clean_job: yes
  http_access: false
