# Buddy's database
---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: Ensure that Postgres packanges are installed
    action: apt name={{item}}
    with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres

  tasks:
  - name: Ensure DB user is ready to go
    postgresql_user: name=buddy password=qwerty role_attr_flags=CREATEDB,SUPERUSER

